name: tflite_flutter
description: TensorFlow Lite Flutter plugin provides an easy, flexible, and fast Dart API to integrate TFLite models in flutter apps across mobile and desktop platforms.
version: 0.9.1
homepage: https://github.com/am15h/tflite_flutter_plugin

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  quiver: ^3.0.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.6.4

flutter:
  plugin:
    platforms:
      android:
        package: com.tfliteflutter.tflite_flutter_plugin
        pluginClass: TfliteFlutterPlugin
      ios:
        pluginClass: TfliteFlutterPlugin
      linux:
        pluginClass: TfliteFlutterPlugin